# Generated by Django 6.0.1 on 2026-02-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.JSONField(blank=True, help_text='Student answers', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
